[tool.pylint.messages_control]

disable = [
    "trailing-whitespace",
    "invalid-name",
    "missing-final-newline",
    "redefined-outer-name"
]

[tool.black]
line-length = 92
target-version = ['py39']
skip-string-normalization=true

[tool.isort]
profile=black